---
- name: Setup Passwordless SSH Access and Sudo Access
  hosts: servers
  become: true
  vars:
    key_path: "/Users/sothanav/Desktop/ssh/dsm"
    key_name: "mpt-prod"
  tasks:
    - name: Copy SSH Key to Remote Servers
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', key_path + '/' + key_name + '.pub') }}"

    - name: Ensure Passwordless Sudo for the User
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'